excluded:
    - Pods
    - .git
    -  Subscriptions

disabled_rules:
    - trailing_whitespace
    - class_delegate_protocol
    - todo
    - cyclomatic_complexity
    - function_body_length
    - generic_type_name
    - identifier_name
    - multiple_closures_with_trailing_closure
    - blanket_disable_command
    - unneeded_synthesized_initializer
    - inclusive_language
    - comment_spacing
    - opening_brace
    - deployment_target

opt_in_rules:
    - overridden_super_call
    - prohibited_super_call
    - explicit_init
    - operator_usage_whitespace

large_tuple: 4

line_length:
    warning: 190

function_parameter_count:
    warning: 10
    error: 15

file_length:
    warning: 600

type_body_length:
        warning: 400
        error: 450

nesting:
    type_level:
        warning: 3
        error: 6
    function_level:
        warning: 5
        error: 6

identifier_name:
    min_length: 1
    max_length: 65

type_name:
    min_length: 3
    max_length: 65
    allowed_symbols: [_]
